# Generated by Django 6.0.3 on 2026-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='save_info',
            field=models.BooleanField(default=True),
        ),
    ]
