# Generated by Django 6.0.3 on 2026-04-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_save_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='same_address',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='save_info',
            field=models.BooleanField(default=False),
        ),
    ]
