# Generated by Django 6.0.3 on 2026-04-28 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_city_area_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.area'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
    ]
