# Generated by Django 6.0.3 on 2026-05-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_client_area_alter_client_city'),
        ('products', '0016_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='faverite_products',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='products.product'),
        ),
    ]
