# Generated by Django 6.0.3 on 2026-05-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_faverite_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='faverite_products',
            new_name='favorite_products',
        ),
    ]
