# Generated by Django 6.0.3 on 2026-03-19 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
