# Generated by Django 6.0.3 on 2026-03-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isbestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='istopfeatured',
            field=models.BooleanField(default=False),
        ),
    ]
