# Generated by Django 6.0.3 on 2026-04-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_isbestseller_product_istopfeatured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-published_date']},
        ),
    ]
