# Generated by Django 6.0.3 on 2026-04-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_occasion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='occasion',
        ),
    ]
