# Generated by Django 6.0.3 on 2026-04-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_occasion_product_occasion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Occasion',
            new_name='occasion',
        ),
    ]
