# Generated by Django 6.0.3 on 2026-04-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_category_parent_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='parent',
            new_name='category',
        ),
    ]
