# Generated by Django 5.2.5 on 2026-06-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_category_id_alter_occasion_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
